; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "Installer LuminaServer"
#define MyAppVersion "1.0"
#define MyAppPublisher "My Company, Inc."
#define MyAppExeName "LuminaServer.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{4C8683F7-2111-4931-BF9C-CF66C2B80C08}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
; Uncomment the following line to use a 64-bit installer.
;SetupArchitecture=x64
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users).
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=D:\installer_Server
OutputBaseFilename=Installer_Server_SETUP
SetupIconFile=C:\Users\Maadized\Desktop\favicon.ico
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "D:\installer_Tutorial_Server\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\installer_Tutorial_Server\bookclub.db"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\installer_Tutorial_Server\D3Dcompiler_47.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\installer_Tutorial_Server\libgcc_s_seh-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\installer_Tutorial_Server\libstdc++-6.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\installer_Tutorial_Server\libwinpthread-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\installer_Tutorial_Server\opengl32sw.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\installer_Tutorial_Server\Qt6Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\installer_Tutorial_Server\Qt6Gui.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\installer_Tutorial_Server\Qt6Network.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\installer_Tutorial_Server\Qt6Pdf.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\installer_Tutorial_Server\Qt6Sql.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\installer_Tutorial_Server\Qt6Svg.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\installer_Tutorial_Server\Qt6Widgets.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\installer_Tutorial_Server\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs; Excludes: "ServerApp.exe"
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

