; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "Installer LuminaClient"
#define MyAppVersion "1.0"
#define MyAppPublisher "My Company, Inc."
#define MyAppExeName "LuminaClient.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{9B4CFD95-7328-456F-93C0-AD904E0009EE}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
; Uncomment the following line to use a 64-bit installer.
;SetupArchitecture=x64
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users).
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=D:\installer_Client
OutputBaseFilename=Installer_Client_SETUP
SetupIconFile=C:\Users\Maadized\Desktop\favicon.ico
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "D:\installer_Tutorial_Client\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\installer_Tutorial_Client\avcodec-61.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\installer_Tutorial_Client\avformat-61.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\installer_Tutorial_Client\avutil-59.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\installer_Tutorial_Client\D3Dcompiler_47.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\installer_Tutorial_Client\libgcc_s_seh-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\installer_Tutorial_Client\libstdc++-6.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\installer_Tutorial_Client\libwinpthread-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\installer_Tutorial_Client\opengl32sw.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\installer_Tutorial_Client\Qt6Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\installer_Tutorial_Client\Qt6Gui.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\installer_Tutorial_Client\Qt6Multimedia.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\installer_Tutorial_Client\Qt6Network.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\installer_Tutorial_Client\Qt6OpenGL.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\installer_Tutorial_Client\Qt6Pdf.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\installer_Tutorial_Client\Qt6PdfWidgets.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\installer_Tutorial_Client\Qt6Qml.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\installer_Tutorial_Client\Qt6QmlMeta.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\installer_Tutorial_Client\Qt6QmlModels.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\installer_Tutorial_Client\Qt6QmlWorkerScript.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\installer_Tutorial_Client\Qt6Quick.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\installer_Tutorial_Client\Qt6Quick3DUtils.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\installer_Tutorial_Client\Qt6QuickWidgets.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\installer_Tutorial_Client\Qt6Svg.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\installer_Tutorial_Client\Qt6Widgets.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\installer_Tutorial_Client\swresample-5.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\installer_Tutorial_Client\swscale-8.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\installer_Tutorial_Client\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

